# Generated by Django 5.0.1 on 2024-01-16 07:23

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="NuevaOrden",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254)),
                (
                    "factura",
                    models.CharField(
                        choices=[("Si", "Si"), ("No", "No")], max_length=3
                    ),
                ),
                ("rfc", models.CharField(blank=True, max_length=13)),
                ("service_type", models.CharField(max_length=255)),
                (
                    "recurrente",
                    models.CharField(
                        choices=[("Si", "Si"), ("No", "No")], max_length=3
                    ),
                ),
                ("volumen", models.DecimalField(decimal_places=1, max_digits=5)),
                ("numero_rastreo", models.CharField(blank=True, max_length=255)),
                (
                    "precio_factura",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("descripcion_mercancia", models.CharField(blank=True, max_length=255)),
                ("tiempo_almacenamiento", models.CharField(blank=True, max_length=255)),
                ("servicios_combinados", models.CharField(blank=True, max_length=255)),
                ("punto_de_carga", models.CharField(blank=True, max_length=255)),
                ("punto_de_descarga", models.CharField(blank=True, max_length=255)),
            ],
        ),
    ]
