# Generated by Django 5.0.1 on 2024-01-16 07:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ordenes", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="nuevaorden",
            name="id",
        ),
        migrations.AddField(
            model_name="nuevaorden",
            name="ordenid",
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="nuevaorden",
            name="numero_rastreo",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="nuevaorden",
            name="precio_factura",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="nuevaorden",
            name="punto_de_carga",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="nuevaorden",
            name="punto_de_descarga",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="nuevaorden",
            name="rfc",
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
        migrations.AlterField(
            model_name="nuevaorden",
            name="service_type",
            field=models.CharField(
                choices=[
                    ("Transporte", "Transporte"),
                    ("Almacenamiento", "Almacenamiento"),
                    ("Distribución", "Distribución"),
                    ("Combinación de servicios", "Combinación de servicios"),
                ],
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="nuevaorden",
            name="servicios_combinados",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="nuevaorden",
            name="tiempo_almacenamiento",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="nuevaorden",
            name="volumen",
            field=models.DecimalField(
                blank=True, decimal_places=1, max_digits=5, null=True
            ),
        ),
    ]
